platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: xenial

inputs:
- name: mlb-datafresh

# outputs:
# - name: 

run:
  path: sh
  args:
    - -exc
    - |
      ls -ltra
      echo Hello world
      uname -sra