resources:
- name: mlb-analytics-ant
  type: git
  source:
    uri: git@github.com:fire-ants/mlb-analytics-ant.git
    branch: ((git-branch))
    private_key: ((git-private-key))
jobs: 
- name: deploy
  plan:
    - aggregate:
      - get: mlb-analytics-ant
        resource: mlb-analytics-ant
        trigger: true
    - task: list_directory
      file: mlb-analytics-ant/ci/tasks/list_directory.yml
    - task: cf-push
      file: mlb-analytics-ant/ci/tasks/cf_push.yml
      params:
        CF_USER: ((cf-username))
        CF_PASSWORD: ((cf-password))
        CF_ORG: ((cf-org))
        CF_SPACE: ((cf-space))
        mlb_db_dbname: ((mlb_db_dbname))
        mlb_db_hostname: ((mlb_db_hostname))
        mlb_db_port: ((mlb_db_port))
        mlb_db_username: ((mlb_db_username))
        mlb_db_password: ((mlb_db_password))
    

- name: run_analytics
  plan: 
    - get: mlb-analytics-ant
      resource: mlb-analytics-ant
    - task: run_analytics-ant
      file: mlb-analytics-ant/ci/tasks/run_analytics.yml
      params:
        CF_USER: ((cf-username))
        CF_PASSWORD: ((cf-password))
        CF_ORG: ((cf-org))
        CF_SPACE: ((cf-space))
        mlb_db_dbname: ((mlb_db_dbname))
        mlb_db_hostname: ((mlb_db_hostname))
        mlb_db_port: ((mlb_db_port))
        mlb_db_username: ((mlb_db_username))
        mlb_db_password: ((mlb_db_password))
