resources:
- name: mlb-analytics-ant
  type: git
  source:
    uri: git@github.com:fire-ants/mlb-analytics-ant.git
    branch: ((git-branch))
    ignore_paths:
    - ci/pipeline.yml
    - README.md
    private_key: ((git-private-key))
jobs:
- name: build-deploy
  plan:
    - aggregate:
      - get: mlb-analytics-ant
        resource: mlb-analytics-ant
        trigger: true
    # list directory is an placeholder for checking something before pushing to CF
    - task: list_directory
      file: mlb-analytics-ant/ci/tasks/list_directory.yml
    - task: cf-push
      file: mlb-analytics-ant/ci/tasks/cf_push.yml
      params:
        CF_USER: ((cf-username))
        CF_PASSWORD: ((cf-password))
        CF_ORG: ((cf-org))
        CF_SPACE: ((cf-space))
        mlb_db_dbname: ((mlb_db_dbname))
        mlb_db_hostname: ((mlb_db_hostname))
        mlb_db_port: ((mlb_db_port))
        mlb_db_username: ((mlb_db_username))
        mlb_db_password: ((mlb_db_password))
        AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
        AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
        AWS_DEFAULT_REGION: ((AWS_DEFAULT_REGION))
- name: run_visualization
  plan: 
    - get: mlb-analytics-ant
      resource: mlb-analytics-ant
    - task: run_visualization
      file: mlb-analytics-ant/ci/tasks/run_analytics.yml
      params:
        CF_USER: ((cf-username))
        CF_PASSWORD: ((cf-password))
        CF_ORG: ((cf-org))
        CF_SPACE: ((cf-space))
